### ISSUE TITLE
Alarming profiling results

### ISSUE THREAD

**Issue by nikita-volkov** [gregorycollins/hashtables#14]
I've been experiencing multiple issues with different implementations of "hashtables" while benchmarking insert operations, so I made a simple profiling script:

``` haskell
import Prelude
import Control.Monad
import qualified Data.HashTable.IO as H


main = do
  c <- H.newSized (10^6) :: IO (H.LinearHashTable Int ())
  forM_ [0..500000] $ \i -> H.insert c i ()
```

Profiling it produces daunting results to say at very least. The program spends most of its time collecting garbage. What's worse is that the `Productivity` percent drops under a progression, i.e. the more rows you insert the larger part of execution time the program spends on GC.

Here are the results:

```
   1,521,188,672 bytes allocated in the heap
   3,599,454,896 bytes copied during GC
      37,996,112 bytes maximum residency (13 sample(s))
       1,404,680 bytes maximum slop
              76 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
  Gen  0      2999 colls,     0 par    4.13s    4.23s     0.0014s    0.0026s
  Gen  1        13 colls,     0 par    0.23s    0.26s     0.0198s    0.0341s

  TASKS: 3 (1 bound, 2 peak workers (2 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.00s  (  0.00s elapsed)
  MUT     time    0.76s  (  0.87s elapsed)
  GC      time    4.28s  (  4.41s elapsed)
  RP      time    0.00s  (  0.00s elapsed)
  PROF    time    0.08s  (  0.08s elapsed)
  EXIT    time    0.00s  (  0.01s elapsed)
  Total   time    5.13s  (  5.28s elapsed)

  Alloc rate    1,992,503,395 bytes per MUT second

  Productivity  14.9% of total user, 14.5% of total elapsed
```

**Comment by gregorycollins** [comment]
@nikita-volkov: BTW I realized I never posted this here: I think I uncovered one reason behind the cuckoo/basic hashtables GC slowdown. GHC's garbage collector scans large mutable arrays in a single thread: https://github.com/ghc/ghc/blob/a11f71eff15ba2706cbb2ee29aaf7350909e0d2f/rts/sm/Scav.c#L161

Since writes to the hashtable are spread across the array, updating more than ~1% of the table between GCs will mean nearly the entire array will be scanned at every stop-the-world GC from a single thread while the others stall. The problem gets worse as the array size grows.

The flag changes I suggested mitigate the issue somewhat, but only because they result in more infrequent GC.
